version: '3.6'
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5555:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
volumes:
  db_data:
